// Z.Design - Real ZIP Export Generator
// Generates downloadable ZIP archives (index.html, styles.css, assets/, README.md)
// from design JSON using JSZip. Follows the same Result-Pattern as pdf-generator.ts.

import JSZip from 'jszip';

interface DesignNode {
  id: string;
  type: string;
  tag?: string;
  content?: string;
  children?: DesignNode[];
  style?: Record<string, unknown>;
  props?: Record<string, unknown>;
  meta?: { name?: string; [key: string]: unknown };
}

interface ZIPExportOptions {
  includeAssets?: boolean; // default true
  includeREADME?: boolean; // default true
  includeDesignJSON?: boolean; // default true
}

interface ZIPGenerationResult {
  success: boolean;
  zipBuffer?: Buffer;
  error?: string;
  metadata?: {
    title: string;
    fileCount: number;
    size: number;
    assetCount: number;
    generatedAt: string;
  };
}

interface ExtractedAsset {
  filename: string;
  buffer: Buffer;
}

/**
 * Counter passed through the tree walk to assign stable CSS class names.
 */
interface ClassCounter {
  n: number;
}

/** CSS class name -> CSS rule body (declarations). */
type CSSMap = Map<string, string>;

/** Converts a camelCase CSS property name to kebab-case (matches pdf-generator.ts). */
function toKebabCase(key: string): string {
  return key.replace(/([A-Z])/g, '-$1').toLowerCase();
}

/**
 * Builds the CSS declarations string for a single node's style object.
 * Returns "" when the node has no usable styles.
 */
function buildDeclarations(style: Record<string, unknown> | undefined): string {
  if (!style || Object.keys(style).length === 0) return '';
  const entries = Object.entries(style)
    .filter(([, v]) => v !== undefined && v !== null && v !== '')
    .map(([key, value]) => {
      const cssKey = toKebabCase(key);
      return `  ${cssKey}: ${value};`;
    });
  return entries.join('\n');
}

/**
 * Recursively converts a DesignNode tree to HTML, collecting CSS rules in `cssMap`.
 * Instead of inline styles it emits `class="zcls-N"` and registers a matching
 * `.zcls-N { ... }` rule. DesignNode is never mutated.
 */
function designNodeToHTMLWithCSS(
  node: DesignNode,
  cssMap: CSSMap,
  counter: ClassCounter,
  indent: number = 0
): string {
  const spaces = '  '.repeat(indent);
  const tag = node.tag || 'div';
  const children = node.children || [];

  // Assign a CSS class for this node if it has styles
  let classAttr = '';
  const declarations = buildDeclarations(node.style);
  if (declarations) {
    counter.n += 1;
    const className = `zcls-${counter.n}`;
    cssMap.set(className, declarations);
    classAttr = ` class="${className}"`;
  }

  // Self-closing tags
  const selfClosingTags = ['img', 'br', 'hr', 'input'];
  if (selfClosingTags.includes(tag) && !children.length && !node.content) {
    return `${spaces}<${tag}${classAttr} />`;
  }

  // Text content nodes
  if (node.type === 'text' || node.type === 'heading') {
    const textContent = node.content || '';
    if (!children.length) {
      return `${spaces}<${tag}${classAttr}>${textContent}</${tag}>`;
    }
  }

  // Button with content
  if (node.type === 'button' && node.content && !children.length) {
    return `${spaces}<${tag}${classAttr}>${node.content}</${tag}>`;
  }

  // Build children HTML
  let innerHTML = '';
  if (node.content && children.length === 0) {
    innerHTML = node.content;
  } else if (children.length > 0) {
    innerHTML =
      '\n' +
      children.map((child) => designNodeToHTMLWithCSS(child, cssMap, counter, indent + 1)).join('\n') +
      `\n${spaces}`;
  }

  return `${spaces}<${tag}${classAttr}>${innerHTML}</${tag}>`;
}

/**
 * Renders the collected CSS map into a complete styles.css document.
 */
function renderStylesCSS(cssMap: CSSMap): string {
  const header = `/* ${'styles.css'} — generated by Z.Design */
/* All component styles extracted from the design tree. */\n\n`;
  const reset = `/* Minimal base reset */
*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

html {
  font-family: 'Inter', system-ui, -apple-system, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  scroll-behavior: smooth;
}

body {
  min-height: 100vh;
  color: #0f172a;
  background-color: #ffffff;
}

img {
  max-width: 100%;
  height: auto;
  display: block;
}

a {
  color: inherit;
  text-decoration: none;
}

button {
  cursor: pointer;
  font-family: inherit;
}

input, textarea, select {
  font-family: inherit;
}

:focus-visible {
  outline: 2px solid #6366f1;
  outline-offset: 2px;
}
`;

  const rules = Array.from(cssMap.entries())
    .map(([cls, body]) => `.${cls} {\n${body}\n}`)
    .join('\n\n');

  return `${header}${reset}\n/* Component styles */\n${rules}\n`;
}

/**
 * Generates a complete standalone HTML document that links to styles.css
 * instead of embedding all component rules inline. A minimal reset is
 * kept in the head for resilience when the file is opened alone.
 */
function generateFullHTML(designJSON: string, projectName: string): { html: string; css: string } {
  let designTree: DesignNode;
  try {
    designTree = JSON.parse(designJSON);
  } catch {
    designTree = { id: 'root', type: 'root', tag: 'div', children: [] };
  }

  const cssMap: CSSMap = new Map();
  const counter: ClassCounter = { n: 0 };
  const bodyContent = designNodeToHTMLWithCSS(designTree, cssMap, counter, 2);
  const css = renderStylesCSS(cssMap);

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName} - Z.Design Export</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
${bodyContent}
</body>
</html>`;

  return { html, css };
}

/**
 * Decodes a data URL into a Buffer. Returns null when the URL is not a data URL
 * or the payload cannot be parsed.
 */
function decodeDataUrl(url: string): { buffer: Buffer; ext: string } | null {
  const match = /^data:([\w/.+-]+);base64,(.*)$/i.exec(url);
  if (!match) return null;
  const mime = match[1];
  const base64 = match[2];
  try {
    const buffer = Buffer.from(base64, 'base64');
    const ext = mimeToExtension(mime);
    return { buffer, ext };
  } catch {
    return null;
  }
}

/**
 * Maps a MIME type string to a file extension, defaulting to .bin.
 */
const MIME_EXT: Record<string, string> = {
  'image/png': '.png',
  'image/jpeg': '.jpg',
  'image/jpg': '.jpg',
  'image/gif': '.gif',
  'image/svg+xml': '.svg',
  'image/webp': '.webp',
  'image/bmp': '.bmp',
  'image/x-icon': '.ico',
  'image/tiff': '.tiff',
};

function mimeToExtension(mime: string): string {
  return MIME_EXT[mime.toLowerCase()] || '.bin';
}

/**
 * Walks the design tree and collects image assets. Data URLs are decoded into
 * binary buffers placed in assets/. External URLs are reported via onWarning
 * (they are left untouched in the HTML).
 */
function extractAssets(
  node: DesignNode,
  assets: ExtractedAsset[],
  onWarning: (msg: string) => void
): void {
  const tag = node.tag || '';
  const isImage = tag === 'img' || node.type === 'image';

  if (isImage && node.props) {
    const src =
      (node.props.src as string | undefined) ||
      (node.props.href as string | undefined) ||
      undefined;

    if (typeof src === 'string' && src.length > 0) {
      if (src.startsWith('data:')) {
        const decoded = decodeDataUrl(src);
        if (decoded) {
          const filename = `asset-${assets.length + 1}${decoded.ext}`;
          assets.push({ filename, buffer: decoded.buffer });
          // Rewrite the node's src to point to the local asset folder.
          // We do NOT mutate the original node; this is a shallow copy for HTML gen.
          node.props = { ...node.props, src: `assets/${filename}` };
        } else {
          onWarning(`Could not decode data URL in node ${node.id}`);
        }
      } else if (/^https?:\/\//i.test(src)) {
        // External URL — leave as reference, warn so the user knows.
        onWarning(`External image URL left as-is in node ${node.id}: ${src}`);
      }
    }
  }

  if (node.children) {
    for (const child of node.children) {
      extractAssets(child, assets, onWarning);
    }
  }
}

/**
 * Builds the README.md content describing the exported project.
 */
function generateREADME(
  projectName: string,
  metadata: { assetCount: number; includeDesignJSON: boolean; generatedAt: string }
): string {
  const treeLine = metadata.includeDesignJSON
    ? '├── design.json     # Raw design tree (machine-readable source)\n'
    : '';
  return `# ${projectName}

Generated by **Z.Design** on ${metadata.generatedAt}.

## File structure
\`\`\`
├── index.html      # Standalone HTML document (links styles.css)
├── styles.css      # All extracted CSS rules (base reset + component classes)
├── assets/         # Images bundled from the design (${metadata.assetCount} file(s))
${treeLine}└── README.md       # This file
\`\`\`

## How to use
1. Unzip into any folder.
2. Open \`index.html\` in a browser — no build step required.
3. \`styles.css\` is linked from \`index.html\`; edit it to restyle components.
4. Images referenced by the design live in \`assets/\`.

## Notes
- Component styles use class names \`.zcls-N\` generated by Z.Design.
- External image URLs (http/https) are left untouched; only embedded data
  URLs were extracted into \`assets/\`.
${metadata.includeDesignJSON ? '- `design.json` is the canonical design tree.\n' : ''}
---
Generated with Z.Design — https://z.design
`;
}

/**
 * Validates ZIP generation prerequisites. jszip has no external runtime
 * dependencies (no native binaries, no browser), so this always succeeds.
 */
export async function validateZIPEnvironment(): Promise<{ valid: boolean; error?: string }> {
  return { valid: true };
}

/**
 * Estimates ZIP generation time based on design complexity.
 * Mirrors the heuristic from estimatePDFGenerationTime.
 */
export function estimateZIPGenerationTime(designJSON: string): number {
  try {
    const design = JSON.parse(designJSON);
    const elementCount = countElements(design);
    // Base 500ms + 0.5ms per element, capped at 4s
    return Math.min(500 + elementCount * 5, 4000);
  } catch {
    return 2000;
  }
}

/**
 * Counts elements in a design tree.
 */
function countElements(node: DesignNode): number {
  let count = 1;
  if (node.children) {
    for (const child of node.children) {
      count += countElements(child);
    }
  }
  return count;
}

/**
 * Generates a ZIP archive from design JSON.
 *
 * @param designJSON - Stringified design tree (DesignNode as root)
 * @param projectName - Human-readable project name
 * @param options - Toggles for assets/README/design.json inclusion
 * @returns ZIPGenerationResult with binary buffer and metadata, or an error.
 */
export async function generateZIP(
  designJSON: string,
  projectName: string,
  options: ZIPExportOptions = {}
): Promise<ZIPGenerationResult> {
  try {
    // Validate input
    if (typeof designJSON !== 'string' || designJSON.length === 0) {
      return {
        success: false,
        error: 'designJSON must be a non-empty string',
      };
    }
    // Ensure it is parseable JSON
    try {
      JSON.parse(designJSON);
    } catch {
      return {
        success: false,
        error: 'designJSON is not valid JSON',
      };
    }

    const includeAssets = options.includeAssets !== false;
    const includeREADME = options.includeREADME !== false;
    const includeDesignJSON = options.includeDesignJSON !== false;

    const warnings: string[] = [];
    const onWarning = (msg: string) => warnings.push(msg);

    // Deep clone the tree so asset path rewriting never mutates caller data.
    let treeClone: DesignNode;
    try {
      treeClone = JSON.parse(designJSON) as DesignNode;
    } catch {
      treeClone = { id: 'root', type: 'root', tag: 'div', children: [] };
    }

    // Extract assets (rewrites src on the clone only)
    const assets: ExtractedAsset[] = [];
    if (includeAssets) {
      extractAssets(treeClone, assets, onWarning);
    }

    // Generate HTML + CSS from the (possibly asset-rewritten) clone
    const { html, css } = generateFullHTML(JSON.stringify(treeClone), projectName);

    // Build README
    const generatedAt = new Date().toISOString();
    const readme = generateREADME(projectName, {
      assetCount: assets.length,
      includeDesignJSON,
      generatedAt,
    });

    // Assemble ZIP
    const zip = new JSZip();
    zip.file('index.html', html);
    zip.file('styles.css', css);
    if (includeREADME) {
      zip.file('README.md', readme);
    }
    if (includeDesignJSON) {
      zip.file('design.json', designJSON);
    }
    if (assets.length > 0) {
      const assetsFolder = zip.folder('assets');
      if (assetsFolder) {
        for (const asset of assets) {
          assetsFolder.file(asset.filename, asset.buffer);
        }
      }
    }

    if (warnings.length > 0) {
      console.warn('[ZIP Generator] Warnings:', warnings);
    }

    const zipBuffer = await zip.generateAsync({
      type: 'nodebuffer',
      compression: 'DEFLATE',
      compressionOptions: { level: 6 },
    });

    // Count files actually added
    const fileCount =
      2 + // index.html + styles.css
      (includeREADME ? 1 : 0) +
      (includeDesignJSON ? 1 : 0) +
      assets.length;

    return {
      success: true,
      zipBuffer,
      metadata: {
        title: projectName,
        fileCount,
        size: zipBuffer.length,
        assetCount: assets.length,
        generatedAt,
      },
    };
  } catch (error) {
    console.error('[ZIP Generator] Error:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error occurred',
    };
  }
}
