// Z.Design — Lessons (Graphify's reflect-loop, adapted for design knowledge)
//
// Inspired by Graphify-Labs/graphify's `save-result → reflect → LESSONS.md`
// pipeline, but implemented natively in TypeScript without any graph DB.
//
// The idea: every design generation produces an outcome signal (score,
// domain, what worked, what failed). These signals accumulate in a flat
// JSONL file. Periodically, `reflect()` distills them into a compact
// `LESSONS.md` using time-decayed scoring + a 2-corroboration threshold.
// The LESSONS.md is then injected into generation prompts as a concise,
// verified knowledge block (~200-400 tokens) — replacing the heavier
// ad-hoc memory blocks and reducing per-generation token cost.
//
// Categories (matching Graphify's model):
//   - PREFERRED: patterns corroborated by ≥2 successful designs
//   - TENTATIVE: seen useful once, not yet corroborated
//   - DEAD_ENDS: patterns that consistently produce low scores
//   - CORRECTIONS: misclassifications the user corrected
//
// Storage:
//   data/lessons.jsonl     — raw outcome signals (append-only)
//   data/LESSONS.md        — distilled, compact knowledge (regenerated by reflect)

import * as fs from 'node:fs';
import * as path from 'node:path';

// ============ Types ============

type Outcome = 'useful' | 'dead_end' | 'corrected';

interface LessonSignal {
  timestamp: number; // epoch ms
  domain: string;
  outcome: Outcome;
  composite: number; // 0-10 scale
  palette?: string;
  concept?: string;
  detail?: string; // what specifically worked/failed
}

interface ScoredPattern {
  key: string; // e.g. "coffee|warm-palette" or "spa|flat-lighting"
  domain: string;
  detail: string;
  score: number; // time-decayed signed score
  count: number; // number of corroborating signals
  avgComposite: number;
}

// ============ Constants ============

const DATA_DIR = path.resolve(process.cwd(), 'data');
const SIGNALS_PATH = path.join(DATA_DIR, 'lessons.jsonl');
const LESSONS_PATH = path.join(DATA_DIR, 'LESSONS.md');
const HALF_LIFE_DAYS = 30; // Graphify's default
const MIN_CORROBORATION = 2; // need ≥2 signals to become "preferred"

// ============ saveResult — record an outcome ============

export async function saveResult(signal: {
  domain: string;
  outcome: Outcome;
  composite: number;
  palette?: string;
  concept?: string;
  detail?: string;
}): Promise<void> {
  try {
    ensureDataDir();
    const entry: LessonSignal = {
      timestamp: Date.now(),
      domain: signal.domain.toLowerCase().trim(),
      outcome: signal.outcome,
      composite: Math.max(0, Math.min(10, signal.composite)),
      palette: signal.palette?.toLowerCase().trim() || undefined,
      concept: signal.concept?.toLowerCase().trim() || undefined,
      detail: signal.detail?.slice(0, 200) || undefined,
    };
    fs.appendFileSync(SIGNALS_PATH, JSON.stringify(entry) + '\n', 'utf8');
  } catch (e) {
    // Memory writes are never fatal.
    console.warn('[lessons] saveResult failed:', e instanceof Error ? e.message : e);
  }
}

// ============ reflect — distill signals into LESSONS.md ============

/**
 * Read all raw signals, apply time-decayed scoring, write LESSONS.md.
 * Deterministic for a given input + now (like Graphify's reflect).
 * Returns the generated markdown string.
 */
export function reflect(): string {
  try {
    const signals = readSignals();
    if (signals.length === 0) return '';

    // Score each (domain, detail) pair with time-decayed signed values.
    const patternScores = new Map<string, ScoredPattern>();
    const now = Date.now();
    const halfLifeMs = HALF_LIFE_DAYS * 24 * 60 * 60 * 1000;

    for (const sig of signals) {
      // Build a composite key from domain + palette/concept/detail
      const detailKey = sig.detail || sig.palette || sig.concept || 'general';
      const key = `${sig.domain}|${detailKey}`;
      const ageMs = now - sig.timestamp;
      const decay = Math.pow(0.5, ageMs / halfLifeMs); // 0-1, half every 30 days
      const sign = sig.outcome === 'useful' ? 1 : sig.outcome === 'dead_end' ? -1 : -0.5;
      const contribution = sign * decay;

      const existing = patternScores.get(key);
      if (existing) {
        existing.score += contribution;
        existing.count += 1;
        existing.avgComposite = (existing.avgComposite * (existing.count - 1) + sig.composite) / existing.count;
      } else {
        patternScores.set(key, {
          key,
          domain: sig.domain,
          detail: detailKey,
          score: contribution,
          count: 1,
          avgComposite: sig.composite,
        });
      }
    }

    // Categorize: preferred (score > 0, count ≥ 2), dead_ends (score < 0), tentative (rest)
    const preferred: ScoredPattern[] = [];
    const deadEnds: ScoredPattern[] = [];
    const tentative: ScoredPattern[] = [];

    for (const p of patternScores.values()) {
      if (p.score >= 0.5 && p.count >= MIN_CORROBORATION) {
        preferred.push(p);
      } else if (p.score <= -0.5 && p.count >= MIN_CORROBORATION) {
        deadEnds.push(p);
      } else if (p.score > 0) {
        tentative.push(p);
      }
    }

    preferred.sort((a, b) => b.score - a.score);
    deadEnds.sort((a, b) => a.score - b.score);
    tentative.sort((a, b) => b.score - a.score);

    // Build the markdown
    const lines: string[] = [
      '# LESSONS — gelernte Muster (auto-generiert)',
      '',
      `Stand: ${new Date().toLocaleString('de-DE')} · ${signals.length} Signale verarbeitet`,
      '',
    ];

    if (preferred.length > 0) {
      lines.push('## Bewährte Muster (≥2 Bestätigungen)');
      for (const p of preferred.slice(0, 10)) {
        lines.push(`- **${p.domain}** — ${p.detail}: Ø${p.avgComposite.toFixed(1)} (${p.count}× bestätigt)`);
      }
      lines.push('');
    }

    if (deadEnds.length > 0) {
      lines.push('## Bekannte Fehlerquellen (vermeiden!)');
      for (const p of deadEnds.slice(0, 10)) {
        lines.push(`- **${p.domain}** — ${p.detail}: Ø${p.avgComposite.toFixed(1)} (${p.count}× negativ)`);
      }
      lines.push('');
    }

    if (tentative.length > 0) {
      lines.push('## Versprechend (noch unbestätigt)');
      for (const p of tentative.slice(0, 5)) {
        lines.push(`- **${p.domain}** — ${p.detail}: Ø${p.avgComposite.toFixed(1)} (1× positiv)`);
      }
      lines.push('');
    }

    const markdown = lines.join('\n');
    try {
      ensureDataDir();
      fs.writeFileSync(LESSONS_PATH, markdown, 'utf8');
    } catch {
      // Write failure is non-fatal — we still return the string.
    }
    return markdown;
  } catch (e) {
    console.warn('[lessons] reflect failed:', e instanceof Error ? e.message : e);
    return '';
  }
}

// ============ loadLessons — inject into prompts ============

let cachedLessons: { value: string; loadedAt: number } | null = null;
const CACHE_TTL_MS = 60_000; // re-read at most once per minute

/**
 * Load the distilled LESSONS.md as a compact string for prompt injection.
 * Cached for 60s to avoid disk reads on every generation.
 * Returns '' if no lessons exist yet (empty file / not generated).
 */
export function loadLessons(): string {
  const now = Date.now();
  if (cachedLessons && now - cachedLessons.loadedAt < CACHE_TTL_MS) {
    return cachedLessons.value;
  }
  try {
    const content = fs.existsSync(LESSONS_PATH) ? fs.readFileSync(LESSONS_PATH, 'utf8') : '';
    cachedLessons = { value: content, loadedAt: now };
    return content;
  } catch {
    return '';
  }
}

/**
 * Build a prompt-ready block from the lessons. Returns '' when empty.
 * The block is prefixed so the LLM knows this is verified knowledge.
 */
export function lessonsToPromptBlock(): string {
  const lessons = loadLessons();
  if (!lessons.trim()) return '';
  return `\n=== GELERENTE MUSTER (verifiziertes Wissen aus vergangenen Designs) ===\n${lessons}\n`;
}

// ============ Internal helpers ============

function ensureDataDir(): void {
  if (!fs.existsSync(DATA_DIR)) {
    fs.mkdirSync(DATA_DIR, { recursive: true });
  }
}

function readSignals(): LessonSignal[] {
  try {
    if (!fs.existsSync(SIGNALS_PATH)) return [];
    const raw = fs.readFileSync(SIGNALS_PATH, 'utf8');
    const lines = raw.split('\n').filter((l) => l.trim());
    const signals: LessonSignal[] = [];
    for (const line of lines) {
      try {
        signals.push(JSON.parse(line) as LessonSignal);
      } catch {
        // Skip malformed lines.
      }
    }
    return signals;
  } catch {
    return [];
  }
}

// ============ Reflect trigger (every Nth generation) ============

let generationCounter = 0;
const REFLECT_INTERVAL = 5; // reflect after every 5th generation

/**
 * Call at the end of each generation. Every Nth call triggers `reflect()`
 * fire-and-forget, updating LESSONS.md. Cheap on non-trigger calls.
 */
export function maybeReflect(): void {
  generationCounter++;
  if (generationCounter % REFLECT_INTERVAL === 0) {
    // Fire-and-forget — don't block the response.
    setImmediate(() => {
      try {
        reflect();
      } catch {
        // Non-fatal.
      }
    });
  }
}
