// AUTO-GENERATED by /tmp/seed-templates.ts — Z.Design template registry.
// Seeded from the 10 flagship designs (showcase/). Each template = our own
// pre-baked design the generator ADAPTS (not regenerates). Grow by promoting
// vision-critique-passing designs into refs/ + appending here.
import type { Template } from './types';

export const TEMPLATES: Template[] = [
  {
    id: 'orathai-thai-spa',
    name: "Orathai Thai Spa",
    label: "orathai-thai-spa · Split-Screen",
    domainFit: ["asian-spa-thai-wellness"],
    palette: {"background":"","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Mulish',sans-serif","body":"inherit"},
    signature: {"layout":"Split-Screen","motion":["Parallax-Tiefe","Cursor-Magnet"],"effect":"Neon-Glow"},
    referencePath: 'orathai-thai-spa.html',
  },
  {
    id: 'forno-nero',
    name: "Forno Nero",
    label: "forno-nero · Cinematic Overlay",
    domainFit: ["coffee-food"],
    palette: {"background":"","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Inter',system-ui,sans-serif","body":"'Fraunces',serif"},
    signature: {"layout":"Cinematic Overlay","motion":["Parallax-Tiefe","Text-Gradient + Glow"],"effect":"Neon-Glow"},
    referencePath: 'forno-nero.html',
  },
  {
    id: 'maison-lumen',
    name: "Maison Lumen",
    label: "maison-lumen · Neo-Brutalismus",
    domainFit: ["fashion-beauty"],
    palette: {"background":"","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Cormorant Garamond',Georgia,serif","body":"'Inter',-apple-system,BlinkMacSystemFont,sans-serif"},
    signature: {"layout":"Neo-Brutalismus","motion":["Animierter Verlauf","Parallax-Tiefe"],"effect":"Neon-Glow"},
    referencePath: 'maison-lumen.html',
  },
  {
    id: 'studio-beton',
    name: "Studio Beton",
    label: "studio-beton · Card-Stack",
    domainFit: ["portfolio-creative-agency"],
    palette: {"background":"#0a0a0a","surface":"","primary":"","accent":"#ff3d14","text":"#f4f1ec"},
    fonts: {"display":"'Inter',system-ui,sans-serif","body":"'Oswald',sans-serif"},
    signature: {"layout":"Card-Stack","motion":["Text-Gradient + Glow","Scroll-Reveal Fade-Up"],"effect":"Glassmorphism"},
    referencePath: 'studio-beton.html',
  },
  {
    id: 'vault3',
    name: "Vault3",
    label: "vault3 · Horizontal-Scroll-Sektion",
    domainFit: ["crypto-web3-fintech"],
    palette: {"background":"#050608","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Inter',system-ui,sans-serif","body":"'Space Grotesk'"},
    signature: {"layout":"Horizontal-Scroll-Sektion","motion":["Cursor-Magnet","Parallax-Tiefe"],"effect":"3D-Hover-Tilt"},
    referencePath: 'vault3.html',
  },
  {
    id: 'puls-festival',
    name: "Puls Festival",
    label: "puls-festival · Mosaik-Galerie",
    domainFit: ["music-events-nightlife"],
    palette: {"background":"","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Inter',system-ui,sans-serif","body":"'JetBrains Mono',monospace"},
    signature: {"layout":"Mosaik-Galerie","motion":["Stagger-Fade","Magnetischer CTA"],"effect":"Glassmorphism"},
    referencePath: 'puls-festival.html',
  },
  {
    id: 'alpenpfad',
    name: "Alpenpfad",
    label: "alpenpfad · Mosaik-Galerie",
    domainFit: ["travel-nature-outdoor"],
    palette: {"background":"","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Inter',system-ui,sans-serif","body":"'Fraunces',serif"},
    signature: {"layout":"Mosaik-Galerie","motion":["Cursor-Magnet","Animierter Verlauf"],"effect":"3D-Hover-Tilt"},
    referencePath: 'alpenpfad.html',
  },
  {
    id: 'kanzlei-nordstern',
    name: "Kanzlei Nordstern",
    label: "kanzlei-nordstern · Cinematic Overlay",
    domainFit: ["law-finance-corporate"],
    palette: {"background":"","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"\"Inter\",system-ui,sans-serif","body":"\"Source Serif Pro\",Georgia,serif}\n  h1,h2,h3,h4{font-family:\"Source Serif Pro\",Georgia,serif"},
    signature: {"layout":"Cinematic Overlay","motion":["Animierter Verlauf","Text-Gradient + Glow"],"effect":"Neon-Glow"},
    referencePath: 'kanzlei-nordstern.html',
  },
  {
    id: 'sattva-yoga',
    name: "Sattva Yoga",
    label: "sattva-yoga · Magazin-Editorial",
    domainFit: ["health-fitness-wellness"],
    palette: {"background":"","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Inter',system-ui,sans-serif","body":"'Fraunces',serif"},
    signature: {"layout":"Magazin-Editorial","motion":["Cursor-Magnet","Animierter Verlauf"],"effect":"Glassmorphism"},
    referencePath: 'sattva-yoga.html',
  },
  {
    id: 'prisma-analytics',
    name: "Prisma Analytics",
    label: "prisma-analytics · Mosaik-Galerie",
    domainFit: ["tech-saas"],
    palette: {"background":"#0a0d12","surface":"","primary":"","accent":"","text":""},
    fonts: {"display":"'Inter',system-ui,sans-serif","body":"'Space Grotesk'"},
    signature: {"layout":"Mosaik-Galerie","motion":["Kinetische Typografie","Parallax-Tiefe"],"effect":"Glassmorphism"},
    referencePath: 'prisma-analytics.html',
  }
];

/** Pick the best template for a design-direction domain (first fit wins). */
export function pickTemplate(domain: string): Template | null {
  return TEMPLATES.find((t) => t.domainFit.some((d) => domain.includes(d) || d.includes(domain))) || TEMPLATES[0] || null;
}

export function templateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}
